{{- if .Values.ingress.traefikEnabled }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "vivaform.fullname" . }}-ingressroute
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.ingress.host }}`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: {{ include "vivaform.fullname" . }}-web
          port: {{ .Values.web.service.port }}
    - match: Host(`{{ .Values.ingress.host }}`) && PathPrefix(`/api`)
      kind: Rule
      services:
        - name: {{ include "vivaform.fullname" . }}-backend
          port: {{ .Values.backend.service.port }}
  tls:
    certResolver: letsencrypt
{{- end }}

