apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vivaform.fullname" . }}-secrets
  labels:
    app: {{ include "vivaform.name" . }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.backend.env.DATABASE_URL | quote }}
  STRIPE_API_KEY: {{ .Values.backend.env.STRIPE_API_KEY | quote }}
  STRIPE_WEBHOOK_SECRET: {{ .Values.backend.env.STRIPE_WEBHOOK_SECRET | quote }}
  STRIPE_PRICE_MONTHLY: {{ .Values.backend.env.STRIPE_PRICE_MONTHLY | quote }}
  STRIPE_PRICE_QUARTERLY: {{ .Values.backend.env.STRIPE_PRICE_QUARTERLY | quote }}
  STRIPE_PRICE_ANNUAL: {{ .Values.backend.env.STRIPE_PRICE_ANNUAL | quote }}
  SMTP_USER: {{ .Values.backend.env.SMTP_USER | quote }}
  SMTP_PASSWORD: {{ .Values.backend.env.SMTP_PASSWORD | quote }}
  REDIS_URL: {{ .Values.backend.env.REDIS_URL | quote }}

