apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vivaform.fullname" . }}-web
  labels:
    app: {{ include "vivaform.name" . }}
    component: web
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "vivaform.name" . }}
      component: web
  template:
    metadata:
      labels:
        app: {{ include "vivaform.name" . }}
        component: web
    spec:
      containers:
        - name: web
          image: "{{ .Values.image.registry }}/{{ .Values.image.webRepository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            {{- range $k, $v in .Values.web.env }}
            - name: {{ $k }}
              value: "{{ $v }}"
            {{- end }}
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vivaform.fullname" . }}-web
spec:
  type: {{ .Values.web.service.type }}
  selector:
    app: {{ include "vivaform.name" . }}
    component: web
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: 80
      name: http

